# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  postgres: